"""content to array

Revision ID: c8da10e39cb1
Revises: bc665eb1def4
Create Date: 2025-07-17 21:43:23.560517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8da10e39cb1'
down_revision: Union[str, Sequence[str], None] = 'bc665eb1def4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corpuses', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('corpuses', 'content',
               existing_type=sa.TEXT(),
               comment='Каждый элемент — строковый фрагмент (абзац, предложение и т.д.)',
               existing_nullable=False)
    op.drop_index(op.f('ix_corpuses_id'), table_name='corpuses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_corpuses_id'), 'corpuses', ['id'], unique=False)
    op.alter_column('corpuses', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Каждый элемент — строковый фрагмент (абзац, предложение и т.д.)',
               existing_nullable=False)
    op.alter_column('corpuses', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
